apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    certmanager.k8s.io/acme-challenge-type: dns01
    certmanager.k8s.io/acme-dns01-provider: cloudflare
  labels:
    app: ldn-statusui
  name: ldn-status-ui-ingress
  namespace: learndevopsnow
spec:
  ingressClassName: nginx
  rules:
    - host: status.learndevopsnow-mm.blog
      http:
        paths:
          - backend:
              service:
                name: ldn-status-ui
                port:
                  number: 80
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - status.learndevopsnow-mm.blog
      secretName: tls-secret-ldn-mm